[general]
email = "your_spacetrack_email"
password = "your_spacetrack_password"
smtp_email = "your_email@example.com"
smtp_password = "your_email_password"
alert_recipient = "your_alert_email@example.com"
