[general]
SPACETRACK_EMAIL = "your_spacetrack_email"
SPACETRACK_PASSWORD = "your_spacetrack_password"
SMTP_EMAIL = "your_email@example.com"
SMTP_PASSWORD = "your_email_password"
ALERT_RECIPIENT = "alert_receiver@example.com"
